# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 607f1bc82e53c8b220afd0b3de769746990538c61f14504feeca932257faf644d0e898a131d70bdeea128e500092ddc62089f9607111576c4e7891b8a9c12b5e

test:
  secret_key_base: 7a5c72f71a7e3612fbc6885fabd850f20c5dd700e3480956a0c7716eabdc946f9765d8d51cbfd1c6a9efc26cf233e6f2552a62139706c46e67c3eeddd9fd1046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
